CREATE TABLE IF NOT EXISTS product (
    [ID] INT IDENTITY(1,1),
    [NAME] NVARCHAR(50) NOT NULL,
    [PRICE] DECIMAL(10,2) NOT NULL,
    [DESCRIPTION] NVARCHAR(100) NULL,
    [REGISTRY_DATE] DATE NOT NULL,
    [USEABLE] BIT NOT NULL
);