CREATE TABLE IF NOT EXISTS product (
    [ID] INTEGER PRIMARY KEY AUTOINCREMENT,
    [NAME] NVARCHAR(50) NOT NULL,
    [PRICE] DECIMAL(10,2) NOT NULL,
    [DESCRIPTION] NVARCHAR(100) NULL,
    [REGISTRYDATE] DATE NOT NULL,
    [USEABLE] BIT NOT NULL
);